### ISSUE TITLE
Monitor channels for posts as an Indigo Event

### ISSUE THREAD

**Issue by indigodomo** [FlyingDiver/Indigo-Slack2#3]
This would allow the user to trigger off of messages received on the specified channel.

**Comment by FlyingDiver** [comment]
Yeah, right now it's a one-way street.  Indigo can post to a channel, but nothing is received.  I'll have to look into what it takes to do that.

**Comment by FlyingDiver** [comment]
This is a significant enhancement.  receiving channel (conversation) events is a different API than posting to a conversation.

**Comment by indigodomo** [comment]
Would make for a nice "glue" between systems particularly since IFTTT has slack built-in. But there will be more options for integration directly with Indigo after v2021.1 so this might not be that important, at least for me, moving forward.

**Comment by FlyingDiver** [comment]
Do you guys use Slack as your dev team discussion platform?

**Comment by indigodomo** [comment]
yes - just started after our jabber server died.

**Comment by FlyingDiver** [comment]
I hesitate to put a lot of effort into the current plugin, as it uses their old deprecated API.  The current API is Python3 only, but with my success with MyQ I might go to the new API using the same method.

**Comment by indigodomo** [comment]
it would be immediately useful for me personally - my new GE Washer/Dryer have WiFi, but getting their notifications into Indigo isn't straight-forward. There is also a Python 3 lib that might work, but I really don't have time to deal with that. They also have IFTTT which can get those into a slack channel, so if I could get that into Indigo then I could do better notifications. But OTOH, not sure if anyone else would find it useful and an audience of one might not be the best use of your time... 🤣

**Comment by FlyingDiver** [comment]
Have you tried using the IFTTT maker to send a web request to Indigo using my HTTPd plugin?  Works fine for kicking off stuff in Indigo based on IFTTT input.

But I'll keep this open, as the Slack plugin really does need this functionality.

**Comment by indigodomo** [comment]
Ah, good point, hadn't thought about that.

**Comment by FlyingDiver** [comment]
I've had some success posting and receiving from the new Slack API using the wrapper Python3 method I used for the MyQ plugin.  I'm still working out some issues where I'm not getting the events from Slack due to blocking on the communications to the plugin.  I'm trying to use asyncio, but I might have to punt that and do my own threading.

**Comment by FlyingDiver** [comment]
Making good progress.  I have my Python3 wrapper working as needed for initial testing.  Now I just need to redo the plugin code to talk to it.

**Comment by indigodomo** [comment]
Cool. Now, if IFTTT were just better than it is (no editing/duplicating/deleting of existing apps - how do these guys stay in business?). Honestly, I couldn't bring myself to go through the creation process again to configure HTTPd and the maker thing, but since my existing applets already write to Slack then it'll be a no brainer if you can get this working.

**Comment by FlyingDiver** [comment]
It's working now.  I'm just trying to figure out if there's an easier way to do the install, since you need to install multiple packages with pip first.  And install the latest Xcode, and run it to install the additional components.  That's the only way to get the current Python3 files.

**Comment by indigodomo** [comment]
Yeah, it's messy. Hopefully something we can solve once we move to Python 3.

**Comment by FlyingDiver** [comment]
I'm actually working on seeing if I can create a virtualenv and populate it from a script the plugin will run, then run the wrapper in the venv.

**Comment by indigodomo** [comment]
That's definitely something that's on the plate when we move to Python 3 - to see if we can figure out how to run plugins in their own virtual environment so that they can more directly control exactly the packages that they want (no versioning conflicts with other plugins that might need the same package but a different version).

**Comment by FlyingDiver** [comment]
Give it a try:  https://github.com/FlyingDiver/Indigo-Slack2/releases/tag/2.0.0

Open to suggestions on additional actions or triggers. I think I'll probably need to add some intelligence to the triggers, maybe like Better Email has.

**Comment by indigodomo** [comment]
Do I need to install something else? When I installed the plugin, the old slack device seemed to be broken even after updating with the new tokens, so I deleted it and started with a new one, and:

```
   Slack 2 Error                   Error in plugin execution ServerReplacedElem:

Traceback (most recent call last):
  File "/Library/Application Support/Perceptive Automation/Indigo 7.5/IndigoPluginHost.app/Contents/Resources/PlugIns/plugin_base.py", line 1179, in deviceUpdated
  File "plugin.py", line 59, in deviceStartComm
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
OSError: [Errno 2] No such file or directory

```
When I restart the plugin:

```
   Reloading plugin "Slack 2 2.0.0"
   Stopping plugin "Slack 2 2.0.0" (pid 38133)
   Slack 2 Error                   exception in deviceStopComm(Bazaar Slack): 1694834566
   Stopped plugin "Slack 2 2.0.0"
   Starting plugin "Slack 2 2.0.0" (pid 38152)
   Started plugin "Slack 2 2.0.0"
   Slack 2 Error                   exception in deviceStartComm(Bazaar Slack): [Errno 2] No such file or directory

```

**Comment by FlyingDiver** [comment]
Does "/usr/bin/python3" exist?  What does "/usr/bin/python3 --version" show?

**Comment by FlyingDiver** [comment]
Doing "Restart in Interactive Shell" usually gives the best error messages.

**Comment by indigodomo** [comment]
Turned on debugging and nothing else - looked at the code and it's likely just an uncaught exception. /usr/bin/python3 exists as does wrapper.py. 

MightyMini-2:~ jay$ /usr/bin/python3 --version
Python 3.8.2

Starting in the interactive shell doesn't yield anything else.

**Comment by FlyingDiver** [comment]
If it's not the python3 file that's a problem, it's wrapper.py.  Check the permissions on wrapper.py in the plugin.  The do this:

` /usr/bin/python3 wrapper.py xx xx`

Should get:

```
jkeenan@Kraken Server Plugin % /usr/bin/python3 wrapper.py xx xx
{"msg": "status", "status": "Clients Created"}
{"msg": "status", "status": "Listener Added"}
{"msg": "status", "status": "Socket Connect Error"}
{"msg": "error", "error": ["The request to the Slack API failed.\nThe server responded with: {'ok': False, 'error': 'invalid_auth'}"]}
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x104a06a90>
```

**Comment by FlyingDiver** [comment]
Interactive Shell is good for catching the errors from the Python3 subprocess.  This error is from the Popen call in the plugin itself.

**Comment by indigodomo** [comment]
Ok, call me super stupid. My production Mac is running Mojave with Python3 installed via the python.org, so it's in /usr/local/bin/python3. When I looked earlier I was looking at my dev Mac running Big Sur with it in /usr/bin/python3. Hur Dur.

Trying to figure out how I can put an alias in /usr/bin but it's locked down pretty tight...

**Comment by indigodomo** [comment]
My production Mac is an old mini which I don't want to try upgrading ATM, so I may just have to wait. Sorry for wasting your time...

**Comment by FlyingDiver** [comment]
Just edit line 58 in plugin.py with the correct path.   I'll probably add a field to the plugin config to override that.

**Comment by FlyingDiver** [comment]
Or grab the latest commit...

**Comment by indigodomo** [comment]
I had already done that and have pip3 installed everything but it looks like maybe there are some OAuth scopes missing:

   Slack 2 Error                   Bazaar Slack: [u"The request to the Slack API failed.\nThe server responded with: {'ok': False, 'error': 'missing_scope', 'needed': 'channels:read,groups:read,mpim:read,im:read', 'provided': 'channels:join,calls:read,chat:write,files:write'}"]

**Comment by indigodomo** [comment]
Crap, had one wrong...

**Comment by indigodomo** [comment]
Ok, got past that. Next issue, when trying to send a slack notification:

   Slack 2 Debug                   Stripped Text: Random stuff
   Slack 2 Debug                   Send wrapper message: {"text": "Random stuff", "cmd": "chat_postMessage", "channel": "C01M8H4ADLJ"}
   Slack 2 Debug                   Bazaar Slack: Received wrapper message: {"msg": "echo", "request": {"text": "Random stuff", "cmd": "chat_postMessage", "channel": "C01M8H4ADLJ"}}
   Slack 2 Debug                   Bazaar Slack: Echo: {u'text': u'Random stuff', u'cmd': u'chat_postMessage', u'channel': u'C01M8H4ADLJ'}
   Slack 2 Debug                   Bazaar Slack: Received wrapper message: {"msg": "error", "error": ["The request to the Slack API failed.\nThe server responded with: {'ok': False, 'error': 'not_in_channel'}"]}
   Slack 2 Error                   Bazaar Slack: [u"The request to the Slack API failed.\nThe server responded with: {'ok': False, 'error': 'not_in_channel'}"]

**Comment by indigodomo** [comment]
When trying to configure an event:

   Slack 2 Debug                   get_channel_list, targetId=971142222, typeId=messageEvent, valuesDict = UiValuesDict : (dict)
   Slack 2 Error                   Error in plugin execution GetUiDynamicList:

Traceback (most recent call last):
  File "plugin.py", line 80, in get_channel_list
KeyError: key slackDevice not found in dict

**Comment by FlyingDiver** [comment]
The not in channel error is probably because you haven't added the bot user to the channel.  See the Wiki for how to do that.

**Comment by FlyingDiver** [comment]
Other error fixed in latest commit (another commit).

**Comment by indigodomo** [comment]
Ok, sending messages is working. However, the event never fires. Nothing in the event log and nothing in the interactive shell. I think I have everything set up, but who knows, it's been a day...

**Comment by FlyingDiver** [comment]
It might be worth running the wrapper on it's own (without the plugin) and seeing if it's reporting any events.  You can run it on the command line, with the two tokens as arguments:
`/usr/local/bin/python3 ./wrapper.py xapp-XXXX xoxb-XXXX`
The only other thing I can think of is that I did something else when configuring the bot on the Slack dashboard I forgot to document.  I'll go through that again.

**Comment by FlyingDiver** [comment]
OK, I deleted all my Slack apps and started a new one exactly per the wiki.  Also not getting events.  So I obviously missed a step somewhere.  Working on it.

**Comment by FlyingDiver** [comment]
Wiki updated.  You need to:
Click on "Event Subscriptions" in the left sidebar.
Click the slider to "Enable Events".
You need the following "Bot User Events": message.channels message.im 
Click on "Save Changes".

**Comment by indigodomo** [comment]
Sweet - that's working, great job. Now all my Inovelli Switches have green chasing or pulsing LEDs when the washer or dryer finishes.

Was I supposed to install those modules as part of the install process or did that get fubar because I was using the wrong python interpreter? In any event, thanks much, SAF has gone up considerably.

**Comment by FlyingDiver** [comment]
Which modules?  The last issue (no events reported) was because I forgot to document the steps to enable events.  :(

**Comment by FlyingDiver** [comment]
So what's the data flow?  Appliance->IFTTT->Slack->Indigo? Yikes.

**Comment by indigodomo** [comment]
Yep - if it works it works! Actually, there is a python3 library to access SmartHQ which is the GE appliance service, so I might could roll a plugin using your pattern. But honestly I don't want to spend any time on that until we get to python3 in Indigo, then maybe. Too many higher priorities.

I had to manually install aiofiles, slack-sdk, aiohttp, and asyncio using pip3.

**Comment by indigodomo** [comment]
Hur dur again - just read your readme and see where it says what to pip install. I guess I was expecting it on the wiki page - Never mind.

**Comment by FlyingDiver** [comment]
Yeah, I should probably move that section.

**Comment by FlyingDiver** [comment]
I have GE appliances, but they must pre-date the service.  Never seen anything about Wifi on them.

**Comment by FlyingDiver** [comment]
I duped that section to the Wiki, just to cover the bases.  I'm going to close this issue, since everything seems to work.  Feel free to open new issues for additional functionality.

**Comment by indigodomo** [comment]
Sorry, spoke too soon: when the IFTTT app writes to the channel, there seems to be a problem:

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "plugin.py", line 144, in wrapper_read
    {'key':'last_event_user',           'value':event['user']},
KeyError: 'user'

```
I suspect that since it's an app it doesn't have an associated user. Here's the debug info:

```
   Slack 2 Debug                   Bazaar Slack: Received wrapper message: {"msg": "received", "type": "events_api", "envelope_id": "57457aa8-27db-41d2-997d-c06da5dba445", "payload": {"token": "G6HP5cl0vFti9htRRS9a6BEY", "team_id": "T01M5EL6YJH", "api_app_id": "A01LTQ468UF", "event": {"type": "message", "subtype": "bot_message", "text": "", "ts": "1613162853.001100", "username": "IFTTT", "icons": {"image_36": "https://a.slack-edge.com/095d8b/img/services/ifttt_36.png", "image_48": "https://a.slack-edge.com/095d8b/img/services/ifttt_48.png", "image_72": "https://a.slack-edge.com/095d8b/img/services/ifttt_72.png"}, "bot_id": "B01M5EMR6JH", "attachments": [{"title": "Dryer cycle done", "text": "Your dryer cycle is complete at February 12, 2021 at 02:47PM", "fallback": "Your dryer cycle is complete at February 12, 2021 at 02:47PM", "mrkdwn_in": ["text", "pretext"]}], "channel": "C01M8H4TCG2", "event_ts": "1613162853.001100", "channel_type": "channel"}, "type": "event_callback", "event_id": "Ev01N657VA8L", "event_time": 1613162853, "authorizations": [{"enterprise_id": null, "team_id": "T01M5EL6YJH", "user_id": "U01N8ACUKRP", "is_bot": true, "is_enterprise_install": false}], "is_ext_shared_channel": false, "event_context": "1-message-T01M5EL6YJH-C01M8H4TCG2"}}
   Slack 2 Debug                   Bazaar Slack: Received events_api (57457aa8-27db-41d2-997d-c06da5dba445)
   Slack 2 Debug                   {
    "api_app_id": "A01LTQ468UF",
    "authorizations": [
        {
            "enterprise_id": null,
            "is_bot": true,
            "is_enterprise_install": false,
            "team_id": "T01M5EL6YJH",
            "user_id": "U01N8ACUKRP"
        }
    ],
    "event": {
        "attachments": [
            {
                "fallback": "Your dryer cycle is complete at February 12, 2021 at 02:47PM",
                "mrkdwn_in": [
                    "text",
                    "pretext"
                ],
                "text": "Your dryer cycle is complete at February 12, 2021 at 02:47PM",
                "title": "Dryer cycle done"
            }
        ],
        "bot_id": "B01M5EMR6JH",
        "channel": "C01M8H4TCG2",
        "channel_type": "channel",
        "event_ts": "1613162853.001100",
        "icons": {
            "image_36": "https://a.slack-edge.com/095d8b/img/services/ifttt_36.png",
            "image_48": "https://a.slack-edge.com/095d8b/img/services/ifttt_48.png",
            "image_72": "https://a.slack-edge.com/095d8b/img/services/ifttt_72.png"
        },
        "subtype": "bot_message",
        "text": "",
        "ts": "1613162853.001100",
        "type": "message",
        "username": "IFTTT"
    },
    "event_context": "1-message-T01M5EL6YJH-C01M8H4TCG2",
    "event_id": "Ev01N657VA8L",
    "event_time": 1613162853,
    "is_ext_shared_channel": false,
    "team_id": "T01M5EL6YJH",
    "token": "G6HP5cl0vFti9htRRS9a6BEY",
    "type": "event_callback"
}


```

**Comment by FlyingDiver** [comment]
Interesting.  Here's the equivalent for a User post to the channel:
```
   Slack 2 Debug                   {
    "api_app_id": "A01MVBEF7NZ",
    "authorizations": [
        {
            "enterprise_id": null,
            "is_bot": true,
            "is_enterprise_install": false,
            "team_id": "T1NEDP5AM",
            "user_id": "U01N4K6LURJ"
        }
    ],
    "event": {
        "blocks": [
            {
                "block_id": "iU4",
                "elements": [
                    {
                        "elements": [
                            {
                                "text": "test",
                                "type": "text"
                            }
                        ],
                        "type": "rich_text_section"
                    }
                ],
                "type": "rich_text"
            }
        ],
        "channel": "C1NE74E79",
        "channel_type": "channel",
        "client_msg_id": "bee6e5c4-04ed-436b-ab01-bd497ff041ee",
        "event_ts": "1613164182.012800",
        "team": "T1NEDP5AM",
        "text": "test",
        "ts": "1613164182.012800",
        "type": "message",
        "user": "U1NEDP5BK"
    },
    "event_context": "1-message-T1NEDP5AM-C1NE74E79",
    "event_id": "Ev01N090GERH",
    "event_time": 1613164182,
    "is_ext_shared_channel": false,
    "team_id": "T1NEDP5AM",
    "token": "fmAerBFX9egYcHKXJy8T4QPo",
    "type": "event_callback"
}
```

**Comment by FlyingDiver** [comment]
So bot messages have a subtype of "bot_message", while user messages have no subtype.  Bogus.

**Comment by FlyingDiver** [comment]
Grab the latest commit and see if that fixes it.

**Comment by indigodomo** [comment]
Almost. I think you need to change line 150 to this:

`{'key':'last_event_user',           'value':user},`

**Comment by FlyingDiver** [comment]
Oops.

**Comment by FlyingDiver** [comment]
Pushed.

**Comment by indigodomo** [comment]
Cool - just got a successful event through IFTTT, so I think we're good.
